### ISSUE TITLE
README.md:18-18: Add brew installation here too.

### ISSUE THREAD

**Issue by 0pdd** [extsoft/pem#15]
The puzzle `11-5a72d067` in [`README.md`](https://github.com/extsoft/pem/blob/master/README.md) (lines 18-18) has to be resolved: "Add brew installation here too."

The puzzle was created by Dmytro Serdiuk on 11-May-17. 

Estimate: 120 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by extsoft** [comment]
`brew` formula is ready: extsoft/homebrew-insight#2 and extsoft/homebrew-insight#3.

**Comment by 0pdd** [comment]
The puzzle `11-5a72d067` has disappeared from the source code, that's why I closed this issue.
