### ISSUE TITLE
Investigate how we can create unit tests 'pem'

### ISSUE THREAD

**Issue by extsoft** [extsoft/pem#50]
Need to provide solutions which allow us to implement unit testing for `pem`. Try to use `pem help` as testing target. All solutions has to be added as comments.

Will used to verify bug #46 and accept #47.

**Comment by AntonKarabaza** [comment]
@extsoft We can use framework `shunit2`(https://github.com/kward/shunit2)

Here is example of script for `pem help` testing:
```
#! /bin/bash

expectedResult=$(<testData.txt)

testPemHelp (){
    actualResult="$(pem help)"
    
    assertEquals "$expectedResult" "$actualResult"
}

. ~/shunit2/source/2.1/src/shunit2
```
Which gives such output:
```
testPemHelp

Ran 1 test.

OK
```

**Comment by ivan-podorozhnyi** [comment]
@extsoft We can use bats (https://github.com/sstephenson/bats)

Here is an example of script for exit code assertion:
```
#!/usr/bin/env bats
@test "testing 'pem help' command" {
  run pem help
  [ "$result" -eq 2 ]
}
```
To run test we need to invoke the bats interpreter with a path to a test file.
Example:
```
bats ~/my_project/test.bats
```
Which gives output:
```
bats test.bats
 ✓ testing 'pem help' command

1 test, 0 failures
```
Here is an example of script for output assertion:
```
#!/usr/bin/env bats
@test "testing 'pem help' command" {
  run pem help
  [[ ${lines[0]} =~ "Unknown command: pem help" ]]
}
```

**Comment by AntonKarabaza** [comment]
@extsoft We can use framework `bash_unit`(https://github.com/pgrange/bash_unit)

Here is example of script for `pem help` testing:
```
#! /bin/bash

expectedResult=$(<~/pem/test/testData.txt)

testPemHelp (){
    actualResult="$(pem help)"
    
    assert_equals "$expectedResult" "$actualResult"
}
```
Which gives such output:
```
Running tests in ~/pem/test/test.sh
Running testPemHelp... SUCCESS ✓ 
```

**Comment by ivan-podorozhnyi** [comment]
@extsoft Another testing framework is provashell (https://github.com/danigiri/provashell)

To run the test we need to execute our script:
```
./test.sh
```
Here is an example of test for output assertion:
```
#!/bin/bash
#@Test
foo() {
    expectedResult=$(<testData.txt)
    actualResult="$(pem help)"   
    assertEquals 'Output is not the same' "$expectedResult" "$actualResult"
}
. ./provashell
```
Which gives output:
```
provashell: Ran 1 of 1 tests
```
If test fails, we can see the error message which we add as a first argument after asserEquals.
```
Output is not the same
provashell: Ran 1 of 1 tests
```

In my opinion bats is better solution as it has several advantages over provashell.
Like special variables $status and $output, skip command, starting all tests inside a folder and so on. Bats also has a bigger team of contributors at GitHub.

**Comment by AntonKarabaza** [comment]
In conclusion, I can say, that mainly `shunit2` and `bash_unit` have similar functionality.
But `shunit2` has against `bash_unit`:
- Skipping tests
- Suites

When the `bash_unit` has:
- More friendly output of testing result.
- Less complicated amount of `assert` functions.

So, if we need powerful complex tool - `shunit2` our choice. If we need lightweight tool, it can be `bash_unit`.

**Comment by extsoft** [comment]
@AntonKarabaza @ivan-podorozhnyi  we will use https://github.com/sstephenson/bats
